import { ICountry } from "../../models";

export const LIST_COUNTRIES: Array<ICountry> = [
  {
    code: "AF",
    imgSrc: "https://flagsapi.com/AF/flat/16.png",
    name: "Afghanistan",
  },
  {
    code: "AL",
    imgSrc: "https://flagsapi.com/AL/flat/16.png",
    name: "Albania",
  },
  {
    code: "DZ",
    imgSrc: "https://flagsapi.com/DZ/flat/16.png",
    name: "Algeria",
  },
  {
    code: "AS",
    imgSrc: "https://flagsapi.com/AS/flat/16.png",
    name: "American Samoa",
  },
  {
    code: "AD",
    imgSrc: "https://flagsapi.com/AD/flat/16.png",
    name: "Andorra",
  },
  { code: "AO", imgSrc: "https://flagsapi.com/AO/flat/16.png", name: "Angola" },
  {
    code: "AI",
    imgSrc: "https://flagsapi.com/AI/flat/16.png",
    name: "Anguilla",
  },
  {
    code: "AG",
    imgSrc: "https://flagsapi.com/AG/flat/16.png",
    name: "Antigua and Barbuda",
  },
  {
    code: "AR",
    imgSrc: "https://flagsapi.com/AR/flat/16.png",
    name: "Argentina",
  },
  {
    code: "AM",
    imgSrc: "https://flagsapi.com/AM/flat/16.png",
    name: "Armenia",
  },
  { code: "AW", imgSrc: "https://flagsapi.com/AW/flat/16.png", name: "Aruba" },
  {
    code: "AU",
    imgSrc: "https://flagsapi.com/AU/flat/16.png",
    name: "Australia",
  },
  {
    code: "AT",
    imgSrc: "https://flagsapi.com/AT/flat/16.png",
    name: "Austria",
  },
  {
    code: "AZ",
    imgSrc: "https://flagsapi.com/AZ/flat/16.png",
    name: "Azerbaijan",
  },
  {
    code: "BH",
    imgSrc: "https://flagsapi.com/BH/flat/16.png",
    name: "Bahrain",
  },
  {
    code: "BD",
    imgSrc: "https://flagsapi.com/BD/flat/16.png",
    name: "Bangladesh",
  },
  {
    code: "BB",
    imgSrc: "https://flagsapi.com/BB/flat/16.png",
    name: "Barbados",
  },
  {
    code: "BY",
    imgSrc: "https://flagsapi.com/BY/flat/16.png",
    name: "Belarus",
  },
  {
    code: "BE",
    imgSrc: "https://flagsapi.com/BE/flat/16.png",
    name: "Belgium",
  },
  { code: "BZ", imgSrc: "https://flagsapi.com/BZ/flat/16.png", name: "Belize" },
  { code: "BJ", imgSrc: "https://flagsapi.com/BJ/flat/16.png", name: "Benin" },
  {
    code: "BM",
    imgSrc: "https://flagsapi.com/BM/flat/16.png",
    name: "Bermuda",
  },
  { code: "BT", imgSrc: "https://flagsapi.com/BT/flat/16.png", name: "Bhutan" },
  {
    code: "BO",
    imgSrc: "https://flagsapi.com/BO/flat/16.png",
    name: "Bolivia",
  },
  {
    code: "BA",
    imgSrc: "https://flagsapi.com/BA/flat/16.png",
    name: "Bosnia and Herzegovina",
  },
  {
    code: "BW",
    imgSrc: "https://flagsapi.com/BW/flat/16.png",
    name: "Botswana",
  },
  { code: "BR", imgSrc: "https://flagsapi.com/BR/flat/16.png", name: "Brazil" },
  {
    code: "VG",
    imgSrc: "https://flagsapi.com/VG/flat/16.png",
    name: "British Virgin Islands",
  },
  { code: "BN", imgSrc: "https://flagsapi.com/BN/flat/16.png", name: "Brunei" },
  {
    code: "BG",
    imgSrc: "https://flagsapi.com/BG/flat/16.png",
    name: "Bulgaria",
  },
  {
    code: "BF",
    imgSrc: "https://flagsapi.com/BF/flat/16.png",
    name: "Burkina Faso",
  },
  {
    code: "BI",
    imgSrc: "https://flagsapi.com/BI/flat/16.png",
    name: "Burundi",
  },
  {
    code: "CV",
    imgSrc: "https://flagsapi.com/CV/flat/16.png",
    name: "Cabo Verde",
  },
  {
    code: "KH",
    imgSrc: "https://flagsapi.com/KH/flat/16.png",
    name: "Cambodia",
  },
  {
    code: "CM",
    imgSrc: "https://flagsapi.com/CM/flat/16.png",
    name: "Cameroon",
  },
  { code: "CA", imgSrc: "https://flagsapi.com/CA/flat/16.png", name: "Canada" },
  {
    code: "KY",
    imgSrc: "https://flagsapi.com/KY/flat/16.png",
    name: "Cayman Islands",
  },
  {
    code: "CF",
    imgSrc: "https://flagsapi.com/CF/flat/16.png",
    name: "Central African Republic",
  },
  { code: "TD", imgSrc: "https://flagsapi.com/TD/flat/16.png", name: "Chad" },
  { code: "CL", imgSrc: "https://flagsapi.com/CL/flat/16.png", name: "Chile" },
  { code: "CN", imgSrc: "https://flagsapi.com/CN/flat/16.png", name: "China" },
  {
    code: "CO",
    imgSrc: "https://flagsapi.com/CO/flat/16.png",
    name: "Colombia",
  },
  {
    code: "KM",
    imgSrc: "https://flagsapi.com/KM/flat/16.png",
    name: "Comoros",
  },
  { code: "CG", imgSrc: "https://flagsapi.com/CG/flat/16.png", name: "Congo" },
  {
    code: "CD",
    imgSrc: "https://flagsapi.com/CD/flat/16.png",
    name: "Congo Democratic Republic",
  },
  {
    code: "CK",
    imgSrc: "https://flagsapi.com/CK/flat/16.png",
    name: "Cook Islands",
  },
  {
    code: "CR",
    imgSrc: "https://flagsapi.com/CR/flat/16.png",
    name: "Costa Rica",
  },
  {
    code: "CI",
    imgSrc: "https://flagsapi.com/CI/flat/16.png",
    name: "Cote d'Ivoire",
  },
  {
    code: "HR",
    imgSrc: "https://flagsapi.com/HR/flat/16.png",
    name: "Croatia",
  },
  { code: "CU", imgSrc: "https://flagsapi.com/CU/flat/16.png", name: "Cuba" },
  {
    code: "CW",
    imgSrc: "https://flagsapi.com/CW/flat/16.png",
    name: "Curaçao",
  },
  { code: "CY", imgSrc: "https://flagsapi.com/CY/flat/16.png", name: "Cyprus" },
  {
    code: "CZ",
    imgSrc: "https://flagsapi.com/CZ/flat/16.png",
    name: "Czech Republic",
  },
  {
    code: "DK",
    imgSrc: "https://flagsapi.com/DK/flat/16.png",
    name: "Denmark",
  },
  {
    code: "DJ",
    imgSrc: "https://flagsapi.com/DJ/flat/16.png",
    name: "Djibouti",
  },
  {
    code: "DM",
    imgSrc: "https://flagsapi.com/DM/flat/16.png",
    name: "Dominica",
  },
  {
    code: "DO",
    imgSrc: "https://flagsapi.com/DO/flat/16.png",
    name: "Dominican Republic",
  },
  {
    code: "TL",
    imgSrc: "https://flagsapi.com/TL/flat/16.png",
    name: "East Timor",
  },
  {
    code: "EC",
    imgSrc: "https://flagsapi.com/EC/flat/16.png",
    name: "Ecuador",
  },
  { code: "EG", imgSrc: "https://flagsapi.com/EG/flat/16.png", name: "Egypt" },
  {
    code: "SV",
    imgSrc: "https://flagsapi.com/SV/flat/16.png",
    name: "El Salvador",
  },
  {
    code: "GQ",
    imgSrc: "https://flagsapi.com/GQ/flat/16.png",
    name: "Equatorial Guinea",
  },
  {
    code: "ER",
    imgSrc: "https://flagsapi.com/ER/flat/16.png",
    name: "Eritrea",
  },
  {
    code: "EE",
    imgSrc: "https://flagsapi.com/EE/flat/16.png",
    name: "Estonia",
  },
  {
    code: "SZ",
    imgSrc: "https://flagsapi.com/SZ/flat/16.png",
    name: "eSwatini",
  },
  {
    code: "ET",
    imgSrc: "https://flagsapi.com/ET/flat/16.png",
    name: "Ethiopia",
  },
  {
    code: "FK",
    imgSrc: "https://flagsapi.com/FK/flat/16.png",
    name: "Falkland Islands",
  },
  {
    code: "FO",
    imgSrc: "https://flagsapi.com/FO/flat/16.png",
    name: "Faroe Islands",
  },
  { code: "FJ", imgSrc: "https://flagsapi.com/FJ/flat/16.png", name: "Fiji" },
  {
    code: "FI",
    imgSrc: "https://flagsapi.com/FI/flat/16.png",
    name: "Finland",
  },
  { code: "FR", imgSrc: "https://flagsapi.com/FR/flat/16.png", name: "France" },
  {
    code: "PF",
    imgSrc: "https://flagsapi.com/PF/flat/16.png",
    name: "French Polynesia",
  },
  { code: "GA", imgSrc: "https://flagsapi.com/GA/flat/16.png", name: "Gabon" },
  { code: "GM", imgSrc: "https://flagsapi.com/GM/flat/16.png", name: "Gambia" },
  {
    code: "GE",
    imgSrc: "https://flagsapi.com/GE/flat/16.png",
    name: "Georgia",
  },
  {
    code: "DE",
    imgSrc: "https://flagsapi.com/DE/flat/16.png",
    name: "Germany",
  },
  { code: "GH", imgSrc: "https://flagsapi.com/GH/flat/16.png", name: "Ghana" },
  {
    code: "GI",
    imgSrc: "https://flagsapi.com/GI/flat/16.png",
    name: "Gibraltar",
  },
  { code: "GR", imgSrc: "https://flagsapi.com/GR/flat/16.png", name: "Greece" },
  {
    code: "GL",
    imgSrc: "https://flagsapi.com/GL/flat/16.png",
    name: "Greenland",
  },
  {
    code: "GD",
    imgSrc: "https://flagsapi.com/GD/flat/16.png",
    name: "Grenada",
  },
  { code: "GU", imgSrc: "https://flagsapi.com/GU/flat/16.png", name: "Guam" },
  {
    code: "GT",
    imgSrc: "https://flagsapi.com/GT/flat/16.png",
    name: "Guatemala",
  },
  {
    code: "GG",
    imgSrc: "https://flagsapi.com/GG/flat/16.png",
    name: "Guernsey",
  },
  { code: "GN", imgSrc: "https://flagsapi.com/GN/flat/16.png", name: "Guinea" },
  {
    code: "GW",
    imgSrc: "https://flagsapi.com/GW/flat/16.png",
    name: "Guinea-Bissau",
  },
  { code: "GY", imgSrc: "https://flagsapi.com/GY/flat/16.png", name: "Guyana" },
  { code: "HT", imgSrc: "https://flagsapi.com/HT/flat/16.png", name: "Haiti" },
  {
    code: "VA",
    imgSrc: "https://flagsapi.com/VA/flat/16.png",
    name: "Holy See (Vatican City)",
  },
  {
    code: "HN",
    imgSrc: "https://flagsapi.com/HN/flat/16.png",
    name: "Honduras",
  },
  {
    code: "HK",
    imgSrc: "https://flagsapi.com/HK/flat/16.png",
    name: "Hong Kong",
  },
  {
    code: "HU",
    imgSrc: "https://flagsapi.com/HU/flat/16.png",
    name: "Hungary",
  },
  {
    code: "IS",
    imgSrc: "https://flagsapi.com/IS/flat/16.png",
    name: "Iceland",
  },
  { code: "IN", imgSrc: "https://flagsapi.com/IN/flat/16.png", name: "India" },
  {
    code: "ID",
    imgSrc: "https://flagsapi.com/ID/flat/16.png",
    name: "Indonesia",
  },
  { code: "IR", imgSrc: "https://flagsapi.com/IR/flat/16.png", name: "Iran" },
  { code: "IQ", imgSrc: "https://flagsapi.com/IQ/flat/16.png", name: "Iraq" },
  {
    code: "IE",
    imgSrc: "https://flagsapi.com/IE/flat/16.png",
    name: "Ireland",
  },
  {
    code: "IM",
    imgSrc: "https://flagsapi.com/IM/flat/16.png",
    name: "Isle of Man",
  },
  { code: "IL", imgSrc: "https://flagsapi.com/IL/flat/16.png", name: "Israel" },
  { code: "IT", imgSrc: "https://flagsapi.com/IT/flat/16.png", name: "Italy" },
  {
    code: "JM",
    imgSrc: "https://flagsapi.com/JM/flat/16.png",
    name: "Jamaica",
  },
  { code: "JP", imgSrc: "https://flagsapi.com/JP/flat/16.png", name: "Japan" },
  { code: "JE", imgSrc: "https://flagsapi.com/JE/flat/16.png", name: "Jersey" },
  { code: "JO", imgSrc: "https://flagsapi.com/JO/flat/16.png", name: "Jordan" },
  {
    code: "KZ",
    imgSrc: "https://flagsapi.com/KZ/flat/16.png",
    name: "Kazakhstan",
  },
  { code: "KE", imgSrc: "https://flagsapi.com/KE/flat/16.png", name: "Kenya" },
  {
    code: "KI",
    imgSrc: "https://flagsapi.com/KI/flat/16.png",
    name: "Kiribati",
  },
  { code: "KW", imgSrc: "https://flagsapi.com/KW/flat/16.png", name: "Kuwait" },
  {
    code: "KG",
    imgSrc: "https://flagsapi.com/KG/flat/16.png",
    name: "Kyrgyzstan",
  },
  { code: "LA", imgSrc: "https://flagsapi.com/LA/flat/16.png", name: "Laos" },
  { code: "LV", imgSrc: "https://flagsapi.com/LV/flat/16.png", name: "Latvia" },
  {
    code: "LB",
    imgSrc: "https://flagsapi.com/LB/flat/16.png",
    name: "Lebanon",
  },
  {
    code: "LS",
    imgSrc: "https://flagsapi.com/LS/flat/16.png",
    name: "Lesotho",
  },
  {
    code: "LR",
    imgSrc: "https://flagsapi.com/LR/flat/16.png",
    name: "Liberia",
  },
  { code: "LY", imgSrc: "https://flagsapi.com/LY/flat/16.png", name: "Libya" },
  {
    code: "LI",
    imgSrc: "https://flagsapi.com/LI/flat/16.png",
    name: "Liechtenstein",
  },
  {
    code: "LT",
    imgSrc: "https://flagsapi.com/LT/flat/16.png",
    name: "Lithuania",
  },
  {
    code: "LU",
    imgSrc: "https://flagsapi.com/LU/flat/16.png",
    name: "Luxembourg",
  },
  { code: "MO", imgSrc: "https://flagsapi.com/MO/flat/16.png", name: "Macau" },
  {
    code: "MK",
    imgSrc: "https://flagsapi.com/MK/flat/16.png",
    name: "Macedonia, Republic of",
  },
  {
    code: "MG",
    imgSrc: "https://flagsapi.com/MG/flat/16.png",
    name: "Madagascar",
  },
  { code: "MW", imgSrc: "https://flagsapi.com/MW/flat/16.png", name: "Malawi" },
  {
    code: "MY",
    imgSrc: "https://flagsapi.com/MY/flat/16.png",
    name: "Malaysia",
  },
  {
    code: "MV",
    imgSrc: "https://flagsapi.com/MV/flat/16.png",
    name: "Maldives",
  },
  { code: "ML", imgSrc: "https://flagsapi.com/ML/flat/16.png", name: "Mali" },
  { code: "MT", imgSrc: "https://flagsapi.com/MT/flat/16.png", name: "Malta" },
  {
    code: "MH",
    imgSrc: "https://flagsapi.com/MH/flat/16.png",
    name: "Marshall Islands",
  },
  {
    code: "MQ",
    imgSrc: "https://flagsapi.com/MQ/flat/16.png",
    name: "Martinique",
  },
  {
    code: "MR",
    imgSrc: "https://flagsapi.com/MR/flat/16.png",
    name: "Mauritania",
  },
  {
    code: "MU",
    imgSrc: "https://flagsapi.com/MU/flat/16.png",
    name: "Mauritius",
  },
  {
    code: "YT",
    imgSrc: "https://flagsapi.com/YT/flat/16.png",
    name: "Mayotte",
  },
  { code: "MX", imgSrc: "https://flagsapi.com/MX/flat/16.png", name: "Mexico" },
  {
    code: "FM",
    imgSrc: "https://flagsapi.com/FM/flat/16.png",
    name: "Micronesia",
  },
  {
    code: "MD",
    imgSrc: "https://flagsapi.com/MD/flat/16.png",
    name: "Moldova",
  },
  { code: "MC", imgSrc: "https://flagsapi.com/MC/flat/16.png", name: "Monaco" },
  {
    code: "MN",
    imgSrc: "https://flagsapi.com/MN/flat/16.png",
    name: "Mongolia",
  },
  {
    code: "ME",
    imgSrc: "https://flagsapi.com/ME/flat/16.png",
    name: "Montenegro",
  },
  {
    code: "MS",
    imgSrc: "https://flagsapi.com/MS/flat/16.png",
    name: "Montserrat",
  },
  {
    code: "MA",
    imgSrc: "https://flagsapi.com/MA/flat/16.png",
    name: "Morocco",
  },
  {
    code: "MZ",
    imgSrc: "https://flagsapi.com/MZ/flat/16.png",
    name: "Mozambique",
  },
  {
    code: "MM",
    imgSrc: "https://flagsapi.com/MM/flat/16.png",
    name: "Myanmar",
  },
  {
    code: "NA",
    imgSrc: "https://flagsapi.com/NA/flat/16.png",
    name: "Namibia",
  },
  { code: "NR", imgSrc: "https://flagsapi.com/NR/flat/16.png", name: "Nauru" },
  { code: "NP", imgSrc: "https://flagsapi.com/NP/flat/16.png", name: "Nepal" },
  {
    code: "NL",
    imgSrc: "https://flagsapi.com/NL/flat/16.png",
    name: "Netherlands",
  },
  {
    code: "NC",
    imgSrc: "https://flagsapi.com/NC/flat/16.png",
    name: "New Caledonia",
  },
  {
    code: "NZ",
    imgSrc: "https://flagsapi.com/NZ/flat/16.png",
    name: "New Zealand",
  },
  {
    code: "NI",
    imgSrc: "https://flagsapi.com/NI/flat/16.png",
    name: "Nicaragua",
  },
  { code: "NE", imgSrc: "https://flagsapi.com/NE/flat/16.png", name: "Niger" },
  {
    code: "NG",
    imgSrc: "https://flagsapi.com/NG/flat/16.png",
    name: "Nigeria",
  },
  {
    code: "KP",
    imgSrc: "https://flagsapi.com/KP/flat/16.png",
    name: "North Korea",
  },
  {
    code: "MP",
    imgSrc: "https://flagsapi.com/MP/flat/16.png",
    name: "Northern Mariana Islands",
  },
  { code: "NO", imgSrc: "https://flagsapi.com/NO/flat/16.png", name: "Norway" },
  { code: "OM", imgSrc: "https://flagsapi.com/OM/flat/16.png", name: "Oman" },
  {
    code: "PK",
    imgSrc: "https://flagsapi.com/PK/flat/16.png",
    name: "Pakistan",
  },
  { code: "PW", imgSrc: "https://flagsapi.com/PW/flat/16.png", name: "Palau" },
  { code: "PA", imgSrc: "https://flagsapi.com/PA/flat/16.png", name: "Panama" },
  {
    code: "PG",
    imgSrc: "https://flagsapi.com/PG/flat/16.png",
    name: "Papua New Guinea",
  },
  {
    code: "PY",
    imgSrc: "https://flagsapi.com/PY/flat/16.png",
    name: "Paraguay",
  },
  { code: "PE", imgSrc: "https://flagsapi.com/PE/flat/16.png", name: "Peru" },
  {
    code: "PH",
    imgSrc: "https://flagsapi.com/PH/flat/16.png",
    name: "Philippines",
  },
  { code: "PL", imgSrc: "https://flagsapi.com/PL/flat/16.png", name: "Poland" },
  {
    code: "PT",
    imgSrc: "https://flagsapi.com/PT/flat/16.png",
    name: "Portugal",
  },
  {
    code: "PR",
    imgSrc: "https://flagsapi.com/PR/flat/16.png",
    name: "Puerto Rico",
  },
  { code: "QA", imgSrc: "https://flagsapi.com/QA/flat/16.png", name: "Qatar" },
  {
    code: "RE",
    imgSrc: "https://flagsapi.com/RE/flat/16.png",
    name: "Reunion",
  },
  {
    code: "RO",
    imgSrc: "https://flagsapi.com/RO/flat/16.png",
    name: "Romania",
  },
  { code: "RU", imgSrc: "https://flagsapi.com/RU/flat/16.png", name: "Russia" },
  { code: "RW", imgSrc: "https://flagsapi.com/RW/flat/16.png", name: "Rwanda" },
  {
    code: "SH",
    imgSrc: "https://flagsapi.com/SH/flat/16.png",
    name: "Saint Helena",
  },
  {
    code: "KN",
    imgSrc: "https://flagsapi.com/KN/flat/16.png",
    name: "Saint Kitts and Nevis",
  },
  {
    code: "LC",
    imgSrc: "https://flagsapi.com/LC/flat/16.png",
    name: "Saint Lucia",
  },
  {
    code: "MF",
    imgSrc: "https://flagsapi.com/MF/flat/16.png",
    name: "Saint Martin",
  },
  {
    code: "PM",
    imgSrc: "https://flagsapi.com/PM/flat/16.png",
    name: "Saint Pierre and Miquelon",
  },
  {
    code: "VC",
    imgSrc: "https://flagsapi.com/VC/flat/16.png",
    name: "Saint Vincent and the Grenadines",
  },
  { code: "WS", imgSrc: "https://flagsapi.com/WS/flat/16.png", name: "Samoa" },
  {
    code: "SM",
    imgSrc: "https://flagsapi.com/SM/flat/16.png",
    name: "San Marino",
  },
  {
    code: "ST",
    imgSrc: "https://flagsapi.com/ST/flat/16.png",
    name: "Sao Tome and Principe",
  },
  {
    code: "SA",
    imgSrc: "https://flagsapi.com/SA/flat/16.png",
    name: "Saudi Arabia",
  },
  {
    code: "SN",
    imgSrc: "https://flagsapi.com/SN/flat/16.png",
    name: "Senegal",
  },
  { code: "RS", imgSrc: "https://flagsapi.com/RS/flat/16.png", name: "Serbia" },
  {
    code: "SC",
    imgSrc: "https://flagsapi.com/SC/flat/16.png",
    name: "Seychelles",
  },
  {
    code: "SL",
    imgSrc: "https://flagsapi.com/SL/flat/16.png",
    name: "Sierra Leone",
  },
  {
    code: "SG",
    imgSrc: "https://flagsapi.com/SG/flat/16.png",
    name: "Singapore",
  },
  {
    code: "SK",
    imgSrc: "https://flagsapi.com/SK/flat/16.png",
    name: "Slovakia",
  },
  {
    code: "SI",
    imgSrc: "https://flagsapi.com/SI/flat/16.png",
    name: "Slovenia",
  },
  {
    code: "SB",
    imgSrc: "https://flagsapi.com/SB/flat/16.png",
    name: "Solomon Islands",
  },
  {
    code: "SO",
    imgSrc: "https://flagsapi.com/SO/flat/16.png",
    name: "Somalia",
  },
  {
    code: "ZA",
    imgSrc: "https://flagsapi.com/ZA/flat/16.png",
    name: "South Africa",
  },
  {
    code: "KR",
    imgSrc: "https://flagsapi.com/KR/flat/16.png",
    name: "South Korea",
  },
  {
    code: "SS",
    imgSrc: "https://flagsapi.com/SS/flat/16.png",
    name: "South Sudan",
  },
  { code: "ES", imgSrc: "https://flagsapi.com/ES/flat/16.png", name: "Spain" },
  {
    code: "LK",
    imgSrc: "https://flagsapi.com/LK/flat/16.png",
    name: "Sri Lanka",
  },
  { code: "SD", imgSrc: "https://flagsapi.com/SD/flat/16.png", name: "Sudan" },
  {
    code: "SR",
    imgSrc: "https://flagsapi.com/SR/flat/16.png",
    name: "Suriname",
  },
  { code: "SE", imgSrc: "https://flagsapi.com/SE/flat/16.png", name: "Sweden" },
  {
    code: "CH",
    imgSrc: "https://flagsapi.com/CH/flat/16.png",
    name: "Switzerland",
  },
  { code: "SY", imgSrc: "https://flagsapi.com/SY/flat/16.png", name: "Syria" },
  { code: "TW", imgSrc: "https://flagsapi.com/TW/flat/16.png", name: "Taiwan" },
  {
    code: "TJ",
    imgSrc: "https://flagsapi.com/TJ/flat/16.png",
    name: "Tajikistan",
  },
  {
    code: "TZ",
    imgSrc: "https://flagsapi.com/TZ/flat/16.png",
    name: "Tanzania",
  },
  {
    code: "TH",
    imgSrc: "https://flagsapi.com/TH/flat/16.png",
    name: "Thailand",
  },
  {
    code: "BS",
    imgSrc: "https://flagsapi.com/BS/flat/16.png",
    name: "The Bahamas",
  },
  { code: "TG", imgSrc: "https://flagsapi.com/TG/flat/16.png", name: "Togo" },
  { code: "TO", imgSrc: "https://flagsapi.com/TO/flat/16.png", name: "Tonga" },
  {
    code: "TT",
    imgSrc: "https://flagsapi.com/TT/flat/16.png",
    name: "Trinidad and Tobago",
  },
  {
    code: "TN",
    imgSrc: "https://flagsapi.com/TN/flat/16.png",
    name: "Tunisia",
  },
  { code: "TR", imgSrc: "https://flagsapi.com/TR/flat/16.png", name: "Turkey" },
  {
    code: "TM",
    imgSrc: "https://flagsapi.com/TM/flat/16.png",
    name: "Turkmenistan",
  },
  {
    code: "TC",
    imgSrc: "https://flagsapi.com/TC/flat/16.png",
    name: "Turks and Caicos Islands",
  },
  { code: "TV", imgSrc: "https://flagsapi.com/TV/flat/16.png", name: "Tuvalu" },
  { code: "UG", imgSrc: "https://flagsapi.com/UG/flat/16.png", name: "Uganda" },
  {
    code: "UA",
    imgSrc: "https://flagsapi.com/UA/flat/16.png",
    name: "Ukraine",
  },
  {
    code: "AE",
    imgSrc: "https://flagsapi.com/AE/flat/16.png",
    name: "United Arab Emirates",
  },
  {
    code: "GB",
    imgSrc: "https://flagsapi.com/GB/flat/16.png",
    name: "United Kingdom",
  },
  {
    code: "US",
    imgSrc: "https://flagsapi.com/US/flat/16.png",
    name: "United States",
  },
  {
    code: "UY",
    imgSrc: "https://flagsapi.com/UY/flat/16.png",
    name: "Uruguay",
  },
  {
    code: "VI",
    imgSrc: "https://flagsapi.com/VI/flat/16.png",
    name: "US Virgin Islands",
  },
  {
    code: "UZ",
    imgSrc: "https://flagsapi.com/UZ/flat/16.png",
    name: "Uzbekistan",
  },
  {
    code: "VU",
    imgSrc: "https://flagsapi.com/VU/flat/16.png",
    name: "Vanuatu",
  },
  {
    code: "VE",
    imgSrc: "https://flagsapi.com/VE/flat/16.png",
    name: "Venezuela",
  },
  {
    code: "VN",
    imgSrc: "https://flagsapi.com/VN/flat/16.png",
    name: "Vietnam",
  },
  {
    code: "WF",
    imgSrc: "https://flagsapi.com/WF/flat/16.png",
    name: "Wallis and Futuna",
  },
  { code: "YE", imgSrc: "https://flagsapi.com/YE/flat/16.png", name: "Yemen" },
  { code: "ZM", imgSrc: "https://flagsapi.com/ZM/flat/16.png", name: "Zambia" },
  {
    code: "ZW",
    imgSrc: "https://flagsapi.com/ZW/flat/16.png",
    name: "Zimbabwe",
  },
];

export const DEFAULT_COUNTRY = LIST_COUNTRIES.find(
  ({ code }) => code === "AU"
) as ICountry;
